# Pull fedora image
FROM fedora:latest
RUN dnf upgrade -y
    && dnf clean all
# Install httpd
RUN dnf install -y httpd
    && dnf clean all
# Copy myinfo.html to the appropriate location
COPY /data /var/www/html/data
# Expose port 80
EXPOSE 80
# Start httpd service
httpd -D FOREGROUND